### ISSUE TITLE
Active bar not display properly

### ISSUE THREAD

**Issue by winniseptiani** [anothem/android-range-seek-bar#76] opened 2016-06-22 07:23 UTC
Hi,
I need help. If i set min selected value the same with min range value and also max selected value the same with max range value then the active bar not displayed. The active bar should be in red color, and the default bar should be in pale grey color. Here is my snippet.

```   private void setPriceRangeValues(long minPrice, long maxPrice) {
        priceRangeBar.setRangeValues(minPrice, maxPrice);
        priceRangeBar.setSelectedMinValue(minPrice);
        priceRangeBar.setSelectedMaxValue(maxPrice);
    }
```

```        <org.florescu.android.rangeseekbar.RangeSeekBar
            android:id="@+id/rangebar_price"
            style="@style/FitWidth"
            android:layout_below="@id/textview_min_price_info"
            android:layout_marginTop="@dimen/search_check_label_text_size"
            rsb:activeColor="@color/button_default"
            rsb:barHeight="@dimen/search_check_container_padding"
            rsb:defaultColor="@color/calendar_border"
            rsb:showLabels="false"
            rsb:thumbDisabled="@drawable/btn_slider"
            rsb:thumbNormal="@drawable/btn_slider"
            rsb:thumbPressed="@drawable/btn_slider"
            rsb:valuesAboveThumbs="false" />
```

The result screenshot:
![screenshot_2016-06-22-13-11-29_ph_com_space](https://cloud.githubusercontent.com/assets/6646273/16257683/331019ea-3884-11e6-9655-f7d2b2351844.jpg)

Thank you for your help

**Comment by anothem** [comment] 2016-06-22 09:34
I'm sorry I don't understand the problem, it seems to be working as intended. If the two thumbs are at min and max respectively, you see the "default" colour, as soon as one moves, you get the "active" colour. If you don't want this behaviour and you want it always active, you should set alwaysActive to true. 

https://github.com/anothem/android-range-seek-bar/blob/master/rangeseekbar/src/main/res/values/attrs.xml#L18

Does that help?

**Comment by winniseptiani** [comment] 2016-06-22 14:28
Yes, it's really help. That's what i mean. Sorry my english is bad. Thank you :).
One more thing, is there any listener for every thumb movement? I want to display progression value, but don't want to use "valuesAboveThumbs". I want to display the view through my own textview. Is that possible?
Currently i use setOnRangeSeekBarChangeListener to set every value changes to the textview, but the listener only listen when the thumb released, not every iteration of thumb movement.

**Comment by anothem** [comment] 2016-06-22 14:34
No, there's no listener for that. You can make your own class that extends this one and then use that. The latest SNAPSHOT build has made some methods set to protected to permit exactly that.

**Comment by winniseptiani** [comment] 2016-06-22 14:38
OK. I'll try it. Thank's a lot for your help. Really appreciate it :) 👍

**Comment by anothem** [comment] 2016-06-22 14:44
No problem :)
I'll close this issue now, but if you run into any other problems feel free to open another.

**Closed by anothem** 2016-06-22 14:44 UTC
